{
    'name' : "Accounting Documents Template",
    'version' : "1.0",
    'author' : "Ed Chu, Simbioz",
    'depends' : ['base','account_move_template' ],
    'installable' : True,
    'application':True,
    'auto_install':False,
    'data': ['static/menu.xml','static/production_services_act.xml','static/reconsilation_document.xml',
             'static/amortization_calculation_dev.xml',
             'static/coefficient_proportional_allocation_vat_credit_setting.xml',
             'static/fixed_assets_index.xml', 'static/retail_sales_report.xml', 'static/transfer_goods.xml',
             'static/tax_invoice.xml', 'static/appendix_1_tax_invoice.xml', 'static/email_document.xml',
             'static/fixed_assets_preparing_transfer.xml',
             'static/modernization.xml', 'static/reflecting_mutual_settlements.xml',
             'static/revaluation_goods_retail.xml',
             'static/appendix_2_tax_invoice.xml', 'static/employees_bank_cards_information2.xml',
             'static/fixed_assets_repairs_modernization.xml',
             'static/order_units_close_accounts_setting.xml', 'static/register_entries_adjustment.xml',
             'static/sales_agent_report.xml',
             'static/transmission.xml', 'static/attorney_power.xml', 'static/employees_bank_cards_information.xml',
             'static/fixed_assets_transfer.xml',
             'static/payment_order_debiting_funds.xml', 'static/registration_advances_accounting.xml',
             'static/sales_commissioner_report.xml',
             'static/work_in_progress_inventory.xml', 'static/equipment_installation_transfer.xml',
             'static/implementation_services_processing.xml', 'static/payment_order_receipt_funds.xml',
             'static/registration_cost_acquisition_proportionally_subject_vat.xml',
             'static/settlements_with_counterparties_inventory.xml',
             'static/business_trips.xml', 'static/expected_confirmed_vat_corrections.xml',
             'static/income_statement.xml',
             'static/pers_income_tax_exemption_app.xml',
             'static/registration_incoming_document.xml',
             'static/shift_production_report.xml', 'static/calculation_coefficients_completing_appendix.xml',
             'static/fixed_assets_commissioning_document.xml', 'static/income_tax_expense_rationing.xml',
             'static/processing_receip.xml',
             'static/regulated_reports_unloading.xml', 'static/standard_balances_adjustment.xml',
             'static/calculation_income_tax.xml',
             'static/fixed_assets_dev.xml', 'static/installation_warranty_terms.xml',
             'static/recalculation_proportional_vat.xml',
             'static/requirement_waybill.xml'],
}
